name: vps_deploy

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: clean
        run: docker-compose down

      - name: Create .env
        run: |
          echo 'PORT=${{ secrets.PORT }}' > .env
          echo 'JOOMLA_DB_PASSWORD=${{ secrets.JOOMLA_DB_PASSWORD }}' >> .env
          echo 'PHP_ADMIN_PORT=${{ secrets.PHP_ADMIN_PORT }}' >> .env

      - name: Run build
        run: docker-compose up -d

      - name: permission setup
        run: |
          docker exec joomsandbox chmod -R 777 /var/www/html
